name: Deploy app to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow write access to gh-pages branch
permissions:
  contents: write

# Allow a single concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Deploy to gh-pages branch
  deploy:
    defaults:
      run:
        working-directory: atlas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          BASE_PATH: ${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: "pr-preview"
          folder: /dist
          force: false
